# File: docker-compose.yml (Versi Perbaikan)

services:
  backend:
    build: .
    ports:
      - "80:8080"
    environment:
      - DB_HOST=${DB_HOST} # Ini akan diisi 'postgres' dari .env
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      postgres: # <-- [UBAH] Ganti dari 'db' jadi 'postgres'
        condition: service_healthy
    restart: always

  postgres: # <-- [UBAH] Ganti nama service dari 'db' jadi 'postgres'
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: